### ISSUE TITLE
The Pose Adjacent Matrix is different from paper.

### ISSUE THREAD

**Issue by BlueAnthony** [geekfeiw/WiSPPN#2] opened 2019-12-12 07:20 UTC
Pose Adjacent Matrix in paper is 3x18x18.
But, Pose Adjacent Matrix in prepare_data.m & train.py is 4x18x18.

**Comment by geekfeiw** [comment] 2020-04-17 03:06
@BlueAnthony   Aha, we compute loss via _c||x-x'||+c||y-y'||_, where c are used twice. The 4th dimension of Pose Adjacent Matrix is a duplicate of its 3rd dimension. We did this for a more efficient code writing.

**Closed as completed** 2020-04-18 02:26 UTC
